version: '3'
services:
  bot:
    build: .
    env_file: .env
    volumes:
      - .:/app
      - ./container_node_modules:/app/node_modules
    command: npm run dev
  redis:
    image: redis:alpine
    volumes:
      - ./data:/data
    ports:
      - 6379:6379